releases:
  - name: '{{ requiredEnv "APP_NAMESPACE" }}'
    namespace: '{{ requiredEnv "APP_NAMESPACE" }}'
    createNamespace: true
    chart: .
    values:
      - values.yaml
      - ecrImageFull: '{{ requiredEnv "IMAGE_FULL_TAG" }}'
